### ISSUE TITLE
Add the .gitignore file

### ISSUE THREAD

**Issue by singh1114** [nexB/scancode-server#1]
We have to add the .gitignore file so that the stuff doesn't get committed automatically.

These things can be added.
- `migrations/`
- `*.pyc`

@RajuKoushik What else can be added in there?
Check [this](https://stackoverflow.com/questions/3719243/recommended-gitignore-file-for-python-projects) out. Do we need this?

**Comment by yasharmaster** [comment]
[Python.gitignore](https://github.com/github/gitignore/blob/master/Python.gitignore) could be helpful.

**Comment by singh1114** [comment]
@yasharmaster I have never seen many of those things. 
@RajuKoushik What do you think of this?

**Comment by steven-esser** [comment]
@singh1114 adding the gitignore would be helpful :)

Also, make sure to add `.idea` to it as well; we normally want to keep personal stuff like IDE configs out of the project's repository.

**Comment by singh1114** [comment]
@majurg OK, I will add what I feel right for now along with .idea and further we can change that in the future.

**Comment by singh1114** [comment]
@RajuKoushik what is the purpose of .DS_Store file in the root directory? Should we put it in the .gitiignore file.

**Comment by pombredanne** [comment]
@singh1114 just delete... you should use the same .gitignore as ScanCode

**Comment by singh1114** [comment]
@pombredanne Yes that makes sense.
