### ISSUE TITLE
Updating Readme file

### ISSUE THREAD

**Issue by chetanya-shrimali** [nexB/scancode-server#100]
Certain issues are there regarding the Readme File

- While installing the requirements it shows error on installing scancode-toolkit==2.0.1. Which I had to install from scancode-toolkit. `python setup.py install`. And no such instructions are given.
- There is an error regarding `pytest-django`. So, I had to comment it and install the requirements.
- No requirement is given as to install `requests` library in virtual env.

**Comment by chetanya-shrimali** [comment]
@pombredanne plz check the issue so that i may send a pr to same!!

**Comment by pombredanne** [comment]
A PR would be welcomed... just do it :)
