### ISSUE TITLE
Reformat the code

### ISSUE THREAD

**Issue by chetanya-shrimali** [nexB/scancode-server#101]
Re-Formatting the code to follow the pip8 style guide i.e. No trailing whitespaces, No more than 79 characters per line etc.

**Comment by singh1114** [comment]
@chetanya-shrimali Follow the discussion in the issue #52 which teaches a good way of showing how you are going to proceed.

**Comment by Monal5031** [comment]
@singh1114 We can use coala in travis checks for this work, and is much better to maintain the code as it points out errors in the PR itself? If you are okay I can do that. We can use its `PEP8Bear` along with `SpaceConsistencyBear`

**Comment by singh1114** [comment]
@Monal5031 Have no idea on how these things work. Please share a good resource which can show them working. And please carry on with what you are suggesting.

Just keep in mind that both of you don't work on the same thing as it will lead to waste of efforts.

**Comment by Monal5031** [comment]
@singh1114 We have integrated coala to check python codes on https://github.com/iiitv/algos and https://github.com/iiitv/ChefLib , you can see the working there.

**Comment by chetanya-shrimali** [comment]
Well, I have already reformatted the code. I just need to send the pr. @singh1114
