### ISSUE TITLE
Integrate celery with the tasks

### ISSUE THREAD

**Issue by singh1114** [nexB/scancode-server#18]
Integrate celery with the time task of scanning.

**Comment by pombredanne** [comment]
@singh1114 can you elaborate about this?

**Comment by singh1114** [comment]
As the scan takes a long time, We decided to put the things in the background. For this, we decided to use `celery`. 
So, the idea was to apply the scan and send the user to some normal page where he will be treated with some string like. Your code is being scanned just wait for a minute. And when the scans were complete tell the user that the scans are complete and show the results on the same page.

Related commits:
https://github.com/nexB/scancode-server/commit/e1c33c204cfdf641772d9d6c643e65a82a2c99a0
https://github.com/nexB/scancode-server/commit/4986bec7edad61f4f182b54e594ee3f5efe3c2e8
