### ISSUE TITLE
Updating the db by the scan results

### ISSUE THREAD

**Issue by RajuKoushik** [nexB/scancode-server#24]

**Comment by pombredanne** [comment]
@singh1114 We need to have a proper description for what this ticket is about

**Comment by singh1114** [comment]
Well, we had a discussion about this a little while ago. We decided to change the way our models looked like. First of all name of `ScanInfo` must be changed to `Scan`. Then, the User model needs to be integrated with the same model. After this, we didn't even needed the `CodeInfo` model and we can attach the fields to `Scan` model. Similar was the case of `ScanFileInfo` and `ScanResult` model. Later we decided to integrate the `MatchedRule` and `MatchedRuleLicense` models to single JSON field. After that, we decided to insert the package as JSON field. 

This was the part which is needed to be done for the models. After that, we also need to take care of the views and tasks which are either trying to get things from the models or want to update things in the models.

Hope I made justice with it. Please add the parts if I have missed something.

**Comment by pombredanne** [comment]
@singh1114 this sounds correct at a high level and is top priority IMHO
