### ISSUE TITLE
Do not store the whole results in JSON field.

### ISSUE THREAD

**Issue by singh1114** [nexB/scancode-server#32]
We cannot hold that many results in a single field. We need to remove the JSON and HTML field.

**Comment by singh1114** [comment]
- [ ] Remove the dependency in from `scanapp/tasks.py`

**Comment by pombredanne** [comment]
I think this ticket is no longer relevant, is it?

**Comment by RajuKoushik** [comment]
@pombredanne  No. Now that @singh1114  is working on the models.

**Comment by singh1114** [comment]
I will close it as soon as we push those commits.
