### ISSUE TITLE
URL scan does not work on non GitHub Links

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-server#83]
I get this error whenever I try using a link on URL scan that is not a GitHub repo:

```
IntegrityError at /urlscan/
null value in column "scan_directory" violates not-null constraint
DETAIL:  Failing row contains (21, https://www.openssl.org/source/openssl-fips-2.0.16.tar.gz, null, null, null, 0, 2017-08-15 23:11:50.961346+00, null, 1).
```

I am using scancode-server from https://github.com/RajuKoushik/scancode-server-1/tree/UrlPasstest, where the changes are for #81

**Comment by RajuKoushik** [comment]
@JonoYang  Would look into it right away.

**Comment by singh1114** [comment]
Yes! the changes are there in #81.

**Comment by singh1114** [comment]
@JonoYang Should we close this for now or is there anything left to be done.

**Comment by JonoYang** [comment]
The issue has been resolved.
